// Generated by https://quicktype.io

export interface LoginResponse {
    codigo:        string | null;
    mensaje:       string | null;
    usuario:          Usuario;
    mensaje_error: string | null;
    token:         string | null;
}

export interface Usuario {
    id:                   number | null;
    usuario:              string | null;
    nombre:               string | null;
    fecha_creacion:       string | null;
    apellido:             string | null;
    correo:               string | null;
    id_institucion:       number | null;
    estado:               string | null;
    foto:                 string | null;
    password:             string | null;
    last_access:          string | null;
    foto_banner:          string | null;
    id_persona:           number | null;
    password2:            string | null;
    id_emprendedor:       number | null;
    id_usuario:           number | null;
    url_foto:             string | null;
    url_foto_banner:      string | null;
    id_asistente_tecnico: number | null;
    id_mentor:            number | null;
    emprendedor:          number | null;
    mesa_servicio:        number | null;
    mentor:               number | null;
    asistencia_tecnica:   number | null;
    administrador:        number | null;
    supervisorProveedor:  number | null;
    asesor:               number | null;
    inscripciones:        Inscripcion[];
}

export interface Inscripcion {
    id_inscripcion:              number | null;
    estado_inscripcion:          string | null;
    fase:                        number | null;
    id_emprendimiento:           number | null;
    nombre_comercial:            string | null;
    nombre_emprendimiento:       string | null;
    ruc_emprendimiento:          string | null;
    razon_social_emprendimiento: string | null;
}

export interface LoginData {
    correo:                     string | null;
    password:                   string | null;
}

export interface MenuResponse {
    codigo:        string | null;
    mensaje:       string | null;
    data:          MenuData[];
    mensaje_error: string | null;
    token:         string | null;
}

export interface MenuData {
    id:            number | null;
    menu:          string | null;
    icono:         string | null;
    url:           string | null;
    estado:        string | null;
    id_menu_padre: number | null;
    agregado:      string | null;
    menus:         Menu[];
    children:      Menu[];
}

export interface DatosEmprendedorResponse {
    codigo:        string | null;
    mensaje:       string | null;
    data:          EmprendedorData;
    mensaje_error: string | null;
    token:         string | null;
}

export interface EmprendedorData {
    persona:              Persona;
    emprendedor:          Emprendedor;
    mentor:               string | null;
    asistente_tecnico:    string | null;
    listaEmprendimientos: any[];
}

export interface Emprendedor {
}

export interface Persona {
    id:                               number | null;
    nombre:                           string | null;
    apellido:                         string | null;
    fecha_nacimiento:                 string | null;
    id_genero:                        number | null;
    id_ciudad:                        number | null;
    email:                            string | null;
    telefono:                         string | null;
    id_situacion_laboral:             number | null;
    tipo_identificacion:              string | null;
    identificacion:                   string | null;
    id_nivel_academico:               number | null;
    id_usuario:                       number | null;
    direccion:                        string | null;
    id_ciudad_domicilio:              number | null;
    fecha_registro:                   Date | null;
    fecha_modificacion:               Date | null;
    id_interes_centro_emprendimiento: number | null;
    telefono_fijo:                    string | null;
    cv:                               string | null;
    estado:                           string | null;
    uso_datos:                        null | boolean;
    perfil:                           string | null;
    frase_perfil:                     string | null;
    compromiso_participante:          null | boolean;
    latitud:                          string | null;
    longitud:                         string | null;
    foto:                             string | null;
    foto_banner:                      string | null;
    pais_natal:                       string | null;
    genero:                           string | null;
    ciudad:                           string | null;
    ciudad_domicilio:                 string | null;
    nivel_academico:                  string | null;
    situacion_laboral:                string | null;
    id_persona:                       number | null;
    id_provincia:                     number | null;
    provincia:                        string | null;
    pais_nacimiento:                  string | null;
    nacionalidad:                     string | null;
    redes_sociales:                   RedesSociales[];
    intereses:                        any[];
}

export interface RedesSociales {
    id:            number | null;
    nombre:        string | null;
    estado:        string | null;
    icono:         string | null;
    id_persona:    number | null;
    id_red_social: number | null;
    red:           string | null;
}

export interface ProgramasInscritosResponse {
    codigo:        string | null;
    mensaje:       string | null;
    data:          ProgramaInscritosData[];
    mensaje_error: string | null;
    token:         string | null;
}

export interface ProgramaInscritosData {
    sub_programa:     SubPrograma;
    fase:             number | null;
    etapa_probada:    boolean | null;
    etapa_anterior:   number | null;
    etapa_nueva:      boolean | null;
    emprendimiento:   Emprendimiento;
    actividades:      Actividades[];
    ejecucion:        boolean | null;
    etapas:           Etapa[];
    pasoEtapa:        string | string;
    etapa:            Etapa;
    inscripcionEtapa: InscripcionEtapa;
    intereses:        any[];
}

export interface Emprendimiento {}

export interface Actividades {
    id_etapa:                               number | null;
    etapa:                                  string | null;
    id_sub_programa:                        number | null;
    estado:                                 string | null;
    inicio:                                 string | null;
    fin:                                    string | null;
    orden:                                  number | null;
    antecesor:                              number | null;
    predecesor:                             number | null;
    icono:                                  string | null;
    logo:                                   string | null;
    banner:                                 string | null;
    plan_trabajo:                           string | null;
    id_actividad_etapa:                     number | null;
    actividad:                              string | null;
    id_tipo_actividad:                      number | null;
    orden_actividad:                        number | null;
    antecesor_actividad:                    number | null;
    predecesor_actividad:                   number | null;
    hora_max:                               number | null;
    hora_min:                               number | null;
    cod_referencia:                         string | null;
    icono_actividad:                        string | null;
    logo_actividad:                         string | null;
    banner_actividad:                       string | null;
    actividad_igual:                        number | null;
    url:                                    string | null;
    aprueba_etapa:                          string | null;
    id_tipo_ejecucion:                      number | null;
    archivo_actividad:                      string | null;
    url_archivo_actividad:                  string | null;
    boton_finalizar:                        string | null;
    boton_guardar:                          string | null;
    componente:                             string | null;
    id_actividad_padre:                     number | null;
    cod_aplicacion_externa:                 number | null;
    cod_trama:                              number | null;
    metodo_api:                             string | null;
    actividad_paralelo:                     string | null;
    codigo_act:                             string | null;
    nemonico:                               string | null;
    mimetype:                               string | null;
    size_max:                               string | null;
    id_actividad_inscripcion:               number | null;
    id_inscripcion:                         number | null;
    cod_referencia_actividad_inscripcion:   string | null;
    fecha_inicio_actividad_inscripcion:     Date | null;
    fecha_fin_actividad_inscripcion:        Date | null;
    fecha_max_inicio_actividad_inscripcion: Date | null;
    tipo_duracion:                          string | null;
    duracion:                               number | null;
    orden_actividad_inscripcion:            number | null;
    antecesor_actividad_inscripcion:        number | null;
    predecesor_actividad_inscripcion:       number | null;
    is_obligatorio:                         boolean | null;
    fecha_registro:                         Date | null;
    fecha_aprobacion:                       Date | null;
    id_usuario_aprobacion:                  number | null;
    tiempo_actividad:                       number | null;
    estado_actividad_inscripcion:           string | null;
    id_mentor:                              number | null;
    id_asistente_tecnico:                   number | null;
    id_actividad_igual_inscripcion:         number | null;
    url_actividad_inscripcion:              null | string;
    estado_actividad:                       string | null;
    id_agenda:                              number | null;
    archivo:                                string | null;
    id_rubrica:                             number | null;
    id_evaluacion:                          number | null;
    id_usuario_mod:                         number | null;
    url_archivo:                            string | null;
    id_actividad_inscripcion_padre:         number | null;
    id_etapa_actividad_inscripcion:         number | null;
    is_agregada_manual:                     string | null;
    id_inscripcion_etapa:                   number | null;
    id_eje_mentoria:                        number | null;
    id_reunion_asig:                        number | null;
    id_asesor:                              number | null;
    id_tipo_asesoria:                       number | null;
    act_aprobo_etapa:                       string | null;
    id_key:                                 number | null;
    id_key_padre:                           number | null;
    child:                                  Actividades[];
}

export interface Etapa {
    id:                 number | null;
    nombre:             string | null;
    id_sub_programa:    number | null;
    estado:             string | null;
    inicio:             string | null;
    fin:                string | null;
    orden:              number | null;
    antecesor:          number | null;
    predecesor:         number | null;
    icono:              string | null;
    logo:               string | null;
    banner:             string | null;
    img1:               string | null;
    plan_trabajo:       string | null;
    version:            string | null;
    max_mentoria:       number | null;
    max_horas_mentoria: number | null;
    color:              string | null;
    id_certificado:     number | null;
    id_etapa:           number | null;
    etapa:              string | null;
    url_logo:           string | null;
    url_banner:         string | null;
    url_icono:          string | null;
}

export interface InscripcionEtapa {
    id:                    number | null;
    id_inscripcion:        number | null;
    id_etapa:              number | null;
    fecha_registro:        Date | null;
    fecha_aprobacion:      Date | null;
    id_usuario_aprobacion: number | null;
    observacion:           string | null;
    estado:                string | null;
    ver_mensaje:           string | null;
    id_etapa_anterior:     number | null;
    version:               string | null;
    certificado_enviado:   number | null;
    certificado_visto:     number | null;
    id_inscripcion_etapa:  number | null;
}

export interface SubPrograma {
    id_inscripcion:     number | null;
    id_sub_programa:    number | null;
    sub_programa:       string | null;
    estado:             string | null;
    version:            string | null;
    icono:              string | null;
    logo:               string | null;
    banner:             string | null;
    id_persona:         number | null;
    id_emprendedor:     number | null;
    id_emprendimiento:  number | null;
    fase:               number | null;
    estado_inscripcion: string | null;
    id_evaluacion_ini:  number | null;
    id_evaluacion_act:  number | null;
}

export interface ResumenActividadesResponse {
    codigo:        string | null;
    mensaje:       string | null;
    data:          ResumenActividadesData;
    mensaje_error: string | null;
    token:         string | null;
}

export interface ResumenActividadesData {
    inscripcion: Inscripcion;
    resumen:     Resumen;
}

export interface Inscripcion {
    etapa:                            number | null;
    etapas:                           number | null;
    id_inscripcion:                   number | null;
    etapaText:                        string | null;
    emprendedor:                      string | null;
    nombre_emprendimiento:            string | null;
    id:                               number | null;
    id_persona:                       number | null;
    id_edicion:                       number | null;
    fecha_registro:                   Date | null;
    id_interes_centro_emprendimiento: number | null;
    fase_asignada:                    number | null;
    fase:                             number | null;
    id_emprendedor:                   number | null;
    id_emprendimiento:                number | null;
    id_evaluacion_ini:                number | null;
    id_evaluacion_act:                number | null;
    estado:                           string | null;
}

export interface Resumen {
    total:       string | null;
    completadas: string | null;
    asignadas:   string | null;
    en_proceso:  string | null;
    avance:      string | null;
    porAvance:   string | null;
}

export interface AvanceEmprendedorResponse {
    codigo:        string | null;
    mensaje:       string | null;
    data:          AvanceEmpprendedorData;
    mensaje_error: string | null;
    token:         string | null;
}

export interface AvanceEmpprendedorData {
    completado: number | null;
    total:      number | null;
    avance:     number | null;
}

export interface AgendaPersonalResponse {
    codigo:        string | null;
    mensaje:       string | null;
    data:          AgendaPersonalData[];
    mensaje_error: string | null;
    token:         string | null;
}

export interface AgendaPersonalData {
    id:                        number | null;
    id_persona:                number | null;
    id_emprendimiento:         number | null;
    id_persona2:               number | null;
    tipo:                      string | null;
    fecha:                     Date | null;
    hora_inicio:               string | null;
    estado:                    string | null;
    tema:                      string | null;
    id_evento:                 number | null;
    hora_fin:                  string | null;
    color:                     string | null;
    fecha_modificacion:        Date | null;
    observacion:               string | null;
    id_motivo_cancelar:        number | null;
    id_tipo_asistencia:        number | null;
    id_actividad:              number | null;
    id_usuario_can:            number | null;
    fecha_registro:            Date | null;
    fecha_cancelacion:         Date | null;
    id_eje_mentoria:           number | null;
    id_agenda_reagendada:      number | null;
    motivo_reagendamiento:     string | null;
    id_usuario_reagendamiento: number | null;
    id_tipo_asesoria:          number | null;
    id_mentor:                 number | null;
    id_asesor:                 number | null;
    id_asistente_tecnico:      number | null;
    id_agenda:                 number | null;
    nombre1:                   string | null;
    nombre2:                   string | null;
    id_reunion:                number | null;
    email1:                    string | null;
    email2:                    string | null;
    start:                     string | null;
    end:                       string | null;
    title:                     string | null;
    backgroundColor:           string | null;
    borderColor:               string | null;
    textColor:                 string | null;
    id_actividad_inscripcion:  number | null;
    motivo_cancelar:           string | null;
    tipo_asistencia:           string | null;
}
